### ISSUE TITLE
full.names() Creatinine Clearance units

### ISSUE THREAD

**Issue by kevindykstra** [qPharmetra/qpToolkit#1]
Currently swaps crcl for Creatinine Clearance (L/min); should be mL/min

full.names = function (x) 
{
  swap(x, Cs(wt, ht, bmi, age, sex, crcl, race), 
       c("Weight (kg)", "Height (cm)", "BMI (kg/m2)", "Age (yr)", "Gender",
         "Creatinine Clearance (L/min)", "Race"))
}

**Comment by bergsmat** [comment]
fixed, created pull request.
