### ISSUE TITLE
issue with align.around.decimal.points 

### ISSUE THREAD

**Issue by krinaj** [qPharmetra/qpToolkit#14]
Hi guys,

Function nm.process.scm is a great one; saves a lot of time in cleaning up outputs for the report.

There seems to be some issue with align.around.decimal.points function, especially in rep() call, leading to error messages when using nm.process.scm. I haven't had a chance to look deeper into this, but wanted to bring it to attention.

Thanks,
Krina

**Comment by bergsmat** [comment]
Hi Krina.

I'll be happy to take a look.  Contact me offline to indicate where I may find some code possibly exhibiting the undesired behavior.

Best,

Tim

**Comment by krinaj** [comment]
Related to #42 and will be taken care of by updates in the nm.process.scm() function.
