### ISSUE TITLE
nm.process.coveffects plots with many levels jitter points onto incorrect crossbars

### ISSUE THREAD

**Issue by jtchittenden** [qPharmetra/qpToolkit#3]
Points and crossbars don't line up.

**Comment by bergsmat** [comment]
Is the problem in nm.process.coveffects(), or is it perhaps in coveff.plot()?  At 14 levels of category, I'm not seeing evidence of overlap.  How many were in use when you saw the problem?  See sample code in iss03: runaNONMEMAnalysis.rmd (branch and block marked iss03).

**Comment by bergsmat** [comment]
Let's close this for now, and re-open if/when we locate a MWE.
