### ISSUE TITLE
nm.process.coveffects has problems if categorical covariates are converted to text

### ISSUE THREAD

**Issue by jtchittenden** [qPharmetra/qpToolkit#4]
for instance, in equations: V1 ~ THETA(1) + THETA(2)*(SEX=="MALE") seems to cause problems.

It may be that the conversion to character is incomplete and breaks don't match actual levels.

**Comment by bergsmat** [comment]
@jtchittenden : in branch iss04, I've stubbed in an example that seems to work.  Can you break it? I've converted GNDR to female/male, and then run the usual processing and plots.

**Comment by bergsmat** [comment]
e4ed96: provisionally fixed.  Happy to reopen for alternate MWE.
